name: conan-package

on:
  workflow_dispatch:
    inputs:
      conan_id:
        required: false
        type: string
        description: 'The full conan package ID, e.g. "curaengine_plugin_infill_generate/1.2.3@ultimaker/stable"'
      create_latest_alias:
        required: true
        default: false
        type: boolean
        description: 'Create latest alias'

jobs:
  conan-package:
    uses: ultimaker/cura-workflows/.github/workflows/conan-package.yml@main
    secrets: inherit