name: Macos Installer
run-name: ${{ inputs.plugin_conan_version }} for Macos-${{ inputs.architecture }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      plugin_conan_version:
        description: 'Plugin Conan Version'
        default: 'curaengine_plugin_fan_by_feature/1.0.0@'
        required: true
        type: string
      conan_args:
        description: 'Conan args: eq.: --require-override'
        default: ''
        required: false
        type: string
      architecture:
        description: 'Architecture'
        required: true
        default: 'X64'
        type: choice
        options:
          - X64
          - ARM64
      operating_system:
        description: 'OS'
        required: true
        default: 'macos-13'
        type: choice
        options:
          - macos-13
  workflow_call:
    inputs:
      plugin_conan_version:
        description: 'Plugin Conan Version'
        default: 'curaengine_plugin_fan_by_feature/1.0.0@'
        required: true
        type: string
      conan_args:
        description: 'Conan args: eq.: --require-override'
        default: ''
        required: false
        type: string
      architecture:
        description: 'Architecture'
        required: true
        default: 'X64'
        type: string
      operating_system:
        description: 'OS'
        required: true
        default: 'macos-13'
        type: string

env:
  CONAN_LOGIN_USERNAME_CURA: ${{ secrets.CONAN_USER }}
  CONAN_PASSWORD_CURA: ${{ secrets.CONAN_PASS }}
  PLUGIN_CONAN_VERSION: ${{ inputs.plugin_conan_version }}

jobs:
  cura-installer-create:
    runs-on: ${{ inputs.operating_system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python and pip
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: .github/workflows/requirements-conan-package.txt

      - name: Install Python requirements for runner
        run: pip install -r .github/workflows/requirements-conan-package.txt

      - name: Cache Conan local repository packages (Bash)
        uses: actions/cache@v3
        with:
          path: |
            /Users/runner/.conan2/p
          key: conan-${{ runner.os }}-${{ runner.arch }}-installer-cache

      - name: Install MacOS system requirements
        run: brew install cmake autoconf automake ninja create-dmg

      - name: Create the default Conan profile
        run: conan profile detect --force

      - name: Get Conan configuration
        run: |
          conan config install https://github.com/Ultimaker/conan-config.git

      - name: Create the Packages (Bash)
        run: conan build . ${{ inputs.conan_args }} --build=missing --update

      - name: Upload the binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ runner.arch }}
          path: |
            build/Release/curaengine_plugin_fan_by_feature
          retention-days: 5

      - name: Upload the cura plugin
        uses: actions/upload-artifact@v4
        with:
          name: macos-cura-plugin-${{ runner.arch }}
          path: |
            CuraEngineFanSpeedByFeatureType/**/*
          retention-days: 5

      - name: Write the run info
        shell: python
        run: |
          import os
          with open("run_info.sh", "w") as f:
              f.writelines(f'echo "PLUGIN_CONAN_VERSION={os.environ["PLUGIN_CONAN_VERSION"]}" >> $GITHUB_ENV\n')

      - name: Upload the run info
        uses: actions/upload-artifact@v4
        with:
          name: macos-run-info-${{ runner.arch }}
          path: |
            run_info.sh
          retention-days: 5
